inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"
    - "vendor/bundle/**/*"
    - "spec/fixtures/**/*"
